parser_console_test: parser_console_test.c ../test_harness.c ../../src/parser.c ../../src/token_stack.c ../../src/free_ast.c ../../src/print_ast.c ../../src/lexer.c 
	gcc parser_console_test.c ../test_harness.c ../../src/parser.c ../../src/token_stack.c ../../src/free_ast.c ../../src/print_ast.c ../../src/lexer.c -o parser_console_test

parser_console_test_debug: parser_console_test.c ../test_harness.c ../../src/parser.c ../../src/token_stack.c ../../src/free_ast.c ../../src/print_ast.c ../../src/lexer.c 
	gcc parser_console_test.c ../test_harness.c ../../src/parser.c ../../src/token_stack.c ../../src/free_ast.c ../../src/print_ast.c ../../src/lexer.c -Wall -Wextra -g -o parser_console_test_debug

