parser_console_test: parser_console_test.c ../test_harness.c ../../src/parser/parser.c ../../src/parser/ast.h ../../src/parser/token_stack.c ../../src/parser/free_ast.c ../../src/parser/print_ast.c ../../src/lexer/lexer.c 
	gcc parser_console_test.c ../test_harness.c ../../src/parser/parser.c ../../src/parser/ast.h ../../src/parser/token_stack.c ../../src/parser/free_ast.c ../../src/parser/print_ast.c ../../src/lexer/lexer.c -o parser_console_test_debug

parser_console_test: parser_console_test.c ../test_harness.c ../../src/parser/parser.c ../../src/parser/ast.h ../../src/parser/token_stack.c ../../src/parser/free_ast.c ../../src/parser/print_ast.c ../../src/lexer/lexer.c 
	gcc parser_console_test.c ../test_harness.c ../../src/parser/parser.c ../../src/parser/ast.h ../../src/parser/token_stack.c ../../src/parser/free_ast.c ../../src/parser/print_ast.c ../../src/lexer/lexer.c -o parser_console_test_debug -Wall -Wextra -g -o parser_console_test
