lexer_tokens_test: lexer_tokens_test.c ../test_harness.c ../../src/lexer.c  
	gcc lexer_tokens_test.c ../test_harness.c ../../src/lexer.c -o lexer_tokens_test

lexer_tokens_test_debug: lexer_tokens_test.c ../test_harness.c ../../src/lexer.c  
	gcc lexer_tokens_test.c ../test_harness.c ../../src/lexer.c -Wall -Wextra -g -o lexer_tokens_test
