lexer_console_test: lexer_console_test.c ../test_harness.c ../../src/lexer.c 
	gcc lexer_console_test.c ../test_harness.c ../../src/lexer.c -o lexer_console_test

lexer_console_test_debug: lexer_console_test.c ../test_harness.c ../../src/lexer.c 
	gcc lexer_console_test.c ../test_harness.c ../../src/lexer.c -Wall -Wextra -g -o lexer_console_test
