parser_ast_test: parser_ast_test.c ../test_harness.c ../../src/parser/parser.c ../../src/parser/ast.h ../../src/parser/token_stack.c ../../src/parser/free_ast.c ../../src/parser/print_ast.c ../../src/lexer/lexer.c 
	gcc parser_ast_test.c ../test_harness.c ../../src/parser/parser.c ../../src/parser/ast.h ../../src/parser/token_stack.c ../../src/parser/free_ast.c ../../src/parser/print_ast.c ../../src/lexer/lexer.c  -o parser_test

parser_ast_test_debug: parser_ast_test.c ../test_harness.c ../../src/parser/parser.c ../../src/parser/ast.h ../../src/parser/token_stack.c ../../src/parser/free_ast.c ../../src/parser/print_ast.c ../../src/lexer/lexer.c 
	gcc parser_ast_test.c ../test_harness.c ../../src/parser/parser.c ../../src/parser/ast.h ../../src/parser/token_stack.c ../../src/parser/free_ast.c ../../src/parser/print_ast.c ../../src/lexer/lexer.c  -Wall -Wextra -g -o parser_test
